include ~/.cache/wal/colors-kitty.conf 
allow_remote_control yes
listen_on unix:/tmp/kitty
font_family JetBrains Mono
bold_font JetBrains Mono Bold
italic_font JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
background_opacity 0.5
shell /usr/bin/zsh
enable_graphics yes
window_padding_width 5 10
